server: 
  port: 9004
spring: 
  application:  
    name: tensquare-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.128:3306/tensquare_article?useUnicode=true&amp;characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  data:
    mongodb:
      host: 192.168.0.128
      database: recruitdb
    redis:
      host: 192.168.0.128
  rabbitmq:
    host: 192.168.0.128
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.128:6868/eureka
  instance:
    prefer-ip-address: true