server:
  port: 9009
spring:
  application:
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.0.128

sms:
  tpl_id : 144304
  key: 5e22a6e69a7a7c8d1e059208d69b0e49


eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
